### ISSUE TITLE
Running test HelloWorld results in a aunit.py failure

### ISSUE THREAD

**Issue by nickponomar** [antoinewaugh/aunit#2]
Trying to run an out of the box example in a Docker build process results in a strange falure:
```
RUN ./aunit.sh test Math
 ---> Running in 307c3ad67707
Traceback (most recent call last):
  File "/aunit-master/test-build/aunit.py", line 495, in <module>
    main(sys.argv[1:])
  File "/aunit-master/test-build/aunit.py", line 480, in main
    contents = load_contents(file) 
  File "/aunit-master/test-build/aunit.py", line 270, in load_contents
    with open(filepath, encoding="utf8", errors="ignore") as f:
TypeError: 'errors' is an invalid keyword argument for this function
/aunit-master/.__test /aunit-master/bin

PYSYS FATAL ERROR: The supplied options did not result in the selection of any tests
/aunit-master/bin
```
With Docker I am using the official Apama builder image from Software AG:
Here is a Dockerfile example:
```
ARG APAMA_VERSION=10.5
ARG APAMA_BUILDER=store/softwareag/apama-builder:${APAMA_VERSION}
# Use the build environment
FROM ${APAMA_BUILDER}
USER root
ADD aunit-master /aunit-master
RUN ["chmod", "+x", "/aunit-master/bin/aunit.sh"]
ENV AUNIT_HOME=/aunit-master
ENV APAMA_JRE=$JAVA_HOME/jre
WORKDIR /aunit-master/bin
RUN ./aunit.sh build
RUN find /aunit-master -type f -exec chmod 777 {} \;
RUN ./aunit.sh test HelloWorld
RUN ./aunit.sh test Math
```
test HelloWorld and test Math result in the same failure

**Comment by antoinewaugh** [comment]
Hi Nick,

Thanks for the issue.

It appears the system python is being used by default, which needs to be overridden in an environment variable AUNIT_PYTHON

Try the following build:

```
ARG APAMA_VERSION=10.5
ARG APAMA_BUILDER=store/softwareag/apama-builder:${APAMA_VERSION}
# Use the build environment
FROM ${APAMA_BUILDER}
USER root
ADD aunit-master /aunit-master
RUN ["chmod", "+x", "/aunit-master/bin/aunit.sh"]
ENV AUNIT_HOME=/aunit-master
ENV APAMA_JRE=$JAVA_HOME/jre
ENV AUNIT_PYTHON=$APAMA_HOME/third_party/python/bin/python3.7
WORKDIR /aunit-master/bin
RUN ./aunit.sh build
RUN find /aunit-master -type f -exec chmod 777 {} \;
RUN ./aunit.sh test HelloWorld
RUN ./aunit.sh test Math
```

**Comment by antoinewaugh** [comment]
By the way great to see aunit being used - any and all issues welcome.

**Comment by nickponomar** [comment]
Hey Antoine,
thanks! It does resolve the issue!
Best,
Nick

**Comment by antoinewaugh** [comment]
Great!
